apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.fullname" . }}
spec:
  selector:
    app: {{ include "demo-app.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
